### ISSUE TITLE
Add `strict` option to warn/fail on unused dependencies

### ISSUE THREAD

**Issue by pdehaan** [mehdishojaei/grunt-amdcheck#8]
Currently, if I run `grunt amdcheck` against our large-ish project, I get the following output:
```
...

Total unused dependencies: 89 in 64 files.
Total processed files: 251

Done, without errors.
```

It may be nice to  have some option (for example, `strict: true` or `allowUnusedDependencies: false`) which will fail the Grunt task if I have any unused dependencies in my project. This would let us break the build if a developer adds an unused dependency in a commit.

We could/should keep the current behavior the same, but it'd be nice to have a stricter option.

**Comment by mehdishojaei** [comment]
Option `strict` with `false` as the default value, added. Upgraded to version 1.3.1

**Comment by mehdishojaei** [comment]
@pdehaan, Option `strict` with `false` as the default value, added. Upgraded to version 1.3.1

**Comment by pdehaan** [comment]
Awesome, works great. Thanks again!
